"""Alerting interfaces and shared helpers."""

from __future__ import annotations

import abc
from dataclasses import dataclass
from datetime import datetime
from typing import Mapping, Sequence

from anomaly_detector.pipeline.models import Event


@dataclass(slots=True)
class Alert:
    """Structured alert generated by the detection pipeline."""

    title: str
    severity: str
    event: Event
    metadata: Mapping[str, str]
    created_at: datetime = datetime.utcnow()


class AlertChannel(abc.ABC):
    """Base interface for alert delivery channels."""

    name: str

    def __init__(self, name: str) -> None:
        self.name = name

    @abc.abstractmethod
    async def send(self, alert: Alert) -> None:
        """Deliver the given alert."""


class AlertDispatcher:
    """Dispatch alerts to multiple channels with basic error isolation."""

    def __init__(self, channels: Sequence[AlertChannel]) -> None:
        self._channels = list(channels)

    async def dispatch(self, alert: Alert) -> None:
        for channel in self._channels:
            try:
                await channel.send(alert)
            except Exception:  # pragma: no cover - defensive catch, logged upstream
                continue
